language: python
sudo: false
dist: bionic  # 18.04
python:
  - 2.7
  - 3.7
  - pypy3
if: (type = push AND branch IN (master)) OR (type = pull_request)
env:
  global:
    - RETRY_TIMEOUT_SECONDS=15
  matrix:
    - TMUX_VERSION=master
    - TMUX_VERSION=3.0a
    - TMUX_VERSION=2.9
    - TMUX_VERSION=2.8
    - TMUX_VERSION=2.8
    - TMUX_VERSION=2.7
    - TMUX_VERSION=2.6
    - TMUX_VERSION=2.5
    - TMUX_VERSION=2.4
    - TMUX_VERSION=2.3
    - TMUX_VERSION=2.2
    - TMUX_VERSION=2.1
    - TMUX_VERSION=2.0
    - TMUX_VERSION=1.9a
    - TMUX_VERSION=1.8
matrix:
  finish_fast: true
  allow_failures:
  - env: TMUX_VERSION=master
cache:
  - pip
  - apt
  - directories:
    - ~/source
    - ~/build
install:
  - pip install poetry
  - poetry install
before_script:
  - mkdir -p ~/source
  - mkdir -p ~/build/tmux-$TMUX_VERSION
  - if [[ ! -d ~/source/tmux-$TMUX_VERSION ]]; then git clone https://github.com/tmux/tmux.git ~/source/tmux-$TMUX_VERSION; fi
  - cd ~/source/tmux-$TMUX_VERSION
  - git checkout $TMUX_VERSION
  - export PATH=$HOME/build/tmux-$TMUX_VERSION/bin:$PATH
  - if [[ $TMUX_VERSION == "master" || ! $(tmux -V | grep $TMUX_VERSION) ]]; then sh autogen.sh; fi
  - if [[ $TMUX_VERSION == "master" || ! $(tmux -V | grep $TMUX_VERSION) ]]; then ./configure --prefix=$HOME/build/tmux-$TMUX_VERSION && make && make install; fi
  - cd $TRAVIS_BUILD_DIR
  - tmux -V
script:
  - poetry run py.test --cov
  - make flake8
addons:
  apt:
    packages:
      - libevent-dev
      - libncurses-dev
after_success:
  - codecov
